name: Security Scan & Test

on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: pip install flask bandit

    - name: Run Bandit (Static Code Analysis)
      run: bandit -r ./app

    - name: Install Trivy
      run: |
        sudo apt update
        sudo apt install -y snapd
        sudo snap install trivy

    - name: Scan source code for vulnerabilities
      run: trivy fs --exit-code 1 --severity HIGH,CRITICAL ./app

    - name: Scan container image for vulnerabilities
      run: |
        docker build -t secure-app ./app
        trivy image --exit-code 1 --severity HIGH,CRITICAL secure-app
